# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BYqNWeFO7Em_cJdqEKTVUi1Z47twkKjE

# 1. Leia dois números, faça a soma e apresente caso seja maior que 15.
"""

N1 = float(input("Insira o primeiro numero: "))
N2 = float(input("Insira o segundo numero: "))

soma = N1 + N2

if soma > 15 :
  print("Seu numero é maior que 15, prossiga!")

"""# 2. Faça um programa que recebendo um valor inteiro, informe se o número é positivo, negativo ou neutro."""

valor = int(float(input("Insira um numero: ")))

if valor > 0 :
  print("Seu numero é positivo")

elif valor < 0 :
  print("Seu numero é negativo")

elif valor == 0 :
  print("Seu numero é neutro")

else :
  print("Insira um numero válido")

"""# 3. Leia a idade e informe se a pessoa é maior ou menor de idade"""

idade = float(input("Insira sua idade: "))

if idade >= 18 :
  print("Voce é maior de idade, prossiga!")

else :
  print("Voce é menor de idade, acesso negado!")

"""# 4. Faça um programa que pergunte a temperatura atual para o usuário e mostre uma mensagem na tela dizendo se está “quente”, “frio” ou “agradável”."""

temp = float(input("Insira a temperatura atual: "))

if temp < 20 :
  print("O clima está frio!")

elif temp >= 20 and temp <= 25 :
  print("O clima está agradável!")

else :
  print("O tempo esta quente!")

"""# 5. Faça um programa em linguagem Python que leia dois números inteiros e informe se estes são iguais ou diferentes"""

N1 = int(float(input("Insira o primeiro numero: ")))
N2 = int(float(input("Insira o segundo numero: ")))

if N1 == N2 :
  print("Os numeros sao iguais!")

else :
  print("Os numeros sao diferentes!")

"""# 6. Escreva um programa que verifique a validade de uma senha fornecida pelo usuário. A senha válida é o número 1234. Devem ser impressas as seguintes mensagens:
# - ACESSO PERMITIDO caso a senha seja válida.
# - ACESSO NEGADO caso a senha seja inválida.

"""

senha = float(input("Insira a sau senha: "))

if senha == 1234 :
  print("Acesso permiido!")

else :
  print("Acesso negado!")

"""# 7. Ler duas notas de um aluno, efetuar a média aritmética e, se a média for maior ou igual a 7, informar que o aluno foi aprovado; se a média for maior ou igual a 5 mas menor do que 7, informar que o aluno está de exame; se a média for menor do que 5 informar que o aluno foi reprovado."""

nota1 = float(input("Insira a primeira nota: "))
nota2 = float(input("Insira a segunda nota: "))

media = (nota1 + nota2) / 2

if media >= 7 :
  print("Parabens, voce foi aprovado!")

elif media >= 5 and media < 7 :
  print("Infelizmente, voce esta de exame!")

else :
  print("Infelizmente voce foi reprovado")

"""# 8. Desenvolva um programa que recebe do usuário o placar de um jogo de futebol (os gols de cada time) e informe se o resultado foi um empate, se a vitória foi do primeiro time ou do segundo time."""

gol_time1 = float(input("Insira a quantidade de gols do primeiro time: "))
gol_time2 = float(input("Insira a quantidade de gols do segundo time: "))

if gol_time1 == gol_time2 :
  print("O jogo foi um empate")

elif gol_time1 > gol_time2 :
  print("O primeiro time ganhou o jogo")

else :
  print("O segundo time ganhou o jogo")

"""# 9. Faça um Programa que pergunte em que turno você estuda. Peça para digitar Mmatutino ou V-Vespertino ou N- Noturno. Imprima a mensagem "Bom Dia!", "Boa Tarde!" ou "Boa Noite!" ou "Valor Inválido!", conforme o caso."""

turno = str(input("Insira o turno que voce estuda, opcoes: M - Matutino, V - Vespertino ou N - Noturno: "))

if turno == "M" or turno == "m" :
  print("Bom dia!")

elif turno == "V" or turno == "v" :
  print("Boa tarde!")

elif turno == "N"
 :
  print("Boa noite!")

else :
  print("Valor invalido")

"""# 10. Faça um programa que solicite ao usuário sua idade, depois disso, exiba a classificação etária de acordo com as faixas de valores:
# - Criança para 0 até 11 anos;
# - Adolescente para 12 até 18 anos;
# - Jovem para 19 até 24 anos;
# - Adulto para 25 até 40 anos;
# - Meia Idade para 41 até 60 anos;
# - Idoso acima de 60 anos
"""

idade = float(input("Insira a sua idade: "))

if idade > 0 and idade <= 11 :
  print("Sua idade encaixa como crianca")

elif idade >= 12 and idade <= 18 :
  print("Sua idade encaixa como adolescente")

elif idade >= 19 and idade <= 24 :
  print("Sua idade encaixa como jovem")

elif idade >= 25 and idade <= 40 :
  print("Sua idade encaixa como adulto")

elif idade >= 41 and idade <= 60 :
  print("Sua idade encaixa como meia idade")

elif idade >= 61:
  print("Sua idade encaixa como idoso")

else :
  print("Insira um valor valido!")

"""# 11. As Organizações Tabajara resolveram dar um aumento de salário aos seus colaboradores e lhe contrataram para desenvolver o programa que calculará os reajustes. Faça um programa que recebe o salário de um colaborador e o reajuste segundo o seguinte critério, baseado no salário atual:
# - salários até RS 280,00 (incluindo) : aumento de 20%
# - salários entre RS 280,00 e RS 700,00 : aumento de 15%
# - salários entre RS 700,00 e RS 1500,00 : aumento de 10%
## - salários de RS 1500,00 em diante : aumento de 5%
# Após o aumento ser realizado, informe na tela:
# - o salário antes do reajuste;
# - o percentual de aumento aplicado;
# - o valor do aumento;
# - o novo salário, após o aumento.

"""

salario = float(input("Insira o salario atual: "))


if salario < 280 :

  porcentagem_aplicada = (20 / 100) * salario
  salario_final = salario + porcentagem_aplicada

  print(f"O salario antes do reajuste é {salario}")
  print("O percentual de aumento será 20%")
  print(f"O valor do aumento será {porcentagem_aplicada}")
  print(f"O novo salario sera {salario_final}")

elif salario >= 280 and salario < 700 :

  porcentagem_aplicada = (15 / 100) * salario
  salario_final = salario + porcentagem_aplicada

  print(f"O salario antes do reajuste é {salario}")
  print("O percentual de aumento será 15%")
  print(f"O valor do aumento será {porcentagem_aplicada}")
  print(f"O novo salario sera {salario_final}")

elif salario >= 700 and salario  < 1500 :

  porcentagem_aplicada = (10 / 100) * salario
  salario_final = salario + porcentagem_aplicada

  print(f"O salario antes do reajuste é {salario}")
  print("O percentual de aumento será 10%")
  print(f"O valor do aumento será {porcentagem_aplicada}")
  print(f"O novo salario sera {salario_final}")

elif salario >= 1500 :
  porcentagem_aplicada = (5 / 100) * salario
  salario_final = salario + porcentagem_aplicada

  print(f"O salario antes do reajuste é {salario}")
  print("O percentual de aumento será 5%")
  print(f"O valor do aumento será {porcentagem_aplicada}")
  print(f"O novo salario sera {salario_final}")

else :
  print("Insira um valor válido!")

"""# 12. Faça um Programa que leia um número e exiba o dia correspondente da semana. (1-Domingo, 2- Segunda, etc.), se digitar outro valor deve aparecer valor inválido."""

dia_semana = float(input("Insira um numero de 1 a 7: "))

if dia_semana == 1 :
  print("Seu numero equivale a Domingo!")

elif dia_semana == 2 :
    print("Seu numero equivale a Segunda-feira!")

elif dia_semana == 3 :
    print("Seu numero equivale a Terca-feira!")

elif dia_semana == 4 :
    print("Seu numero equivale a Quarta-feira!")

elif dia_semana == 5 :
    print("Seu numero equivale a Quinta-feira!")

elif dia_semana == 6 :
    print("Seu numero equivale a Sexta-feira!")

elif dia_semana == 7 :
    print("Seu numero equivale a Sabado!")

else :
  print("Insira um numero valido!")

"""# 13. Faça um programa que pergunte ao usuário se ele quer passar uma temperatura de Fahrenheit para Celsius ou de Celsius para Fahrenheit, e que, a partir da resposta do usuário, faça a devida conversão."""

grau = float(input("Ola selecione uma opcao:\nFahrenheit para Celsius (1)\nCelsius para Fahrenheit (2)\n"))

if grau == 1 :
  opcao1 = float(input("Insira a temperatura  "))

  temperatura_c_f = (opcao1 - 32) / 1.8
  print(f"A temperatura final fica {temperatura_c_f} graus Celsius")

elif grau ==  2 :

  opcao2 = float(input("Insira a temperatura  "))

  temperatura_f_c = (opcao2 * 1.8) + 32
  print(f"A temperatura final fica {temperatura_f_c} graus Fahrenheit")

else :
  print("Insira um valor valido")

"""# 14. Faça um programa que receba a idade de uma pessoa e imprima sua condição (obrigatória, optativa ou proibida), em relação ao ato de votar, conforme apresentado abaixo:
# - Pessoas com idade menor que 16 anos são proibidas de votar
# (proibido);
# - Pessoas com idade igual a 16 e menor que 18 anos não são obrigadas a votar
# (optativo);
# - Pessoas com idade igual a 18 e menor que 65 anos são obrigadas a votar
# (obrigatório)
# - Pessoas com idade igual ou maior a 65 anos não são obrigadas a votar (optativo)

"""

idade = float(input("Insira sua idade "))

if idade < 16 :
  print("PROIBIDO votar")

elif idade >= 16 and idade < 18 :
  print("OPTATIVO votar")

elif idade >= 18 and idade < 65 :
  print("OBRIGATORIO votar")

elif idade >= 65 :
  print("OPTATIVO votar")

else :
  print("Insira uma idade valida!")

"""# 15. Faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As perguntas são:

# - “Telefonou para a vítima? “
# - “Esteve no local do crime?”
# - “Mora perto da vítima? “
# - “Devia para a vítima? “
# - “Já trabalhou com a vítima? “

# O programa deve no final emitir uma classificação sobre a participação da pessoa no crime. Se a pessoa responder positivamente a 2 questões ela deve ser classificada como “Suspeita”, entre 3 e 4 como “Cúmplice” e 5 como “Assassino“. Caso contrário, ele será classificado como “Inocente“
"""

sim = 0

resposta1 = (input("Telefonou para a vítima?"))
sim += 1

resposta2 = (input("Esteve no local do crime?"))
sim += 1

resposta3 = (input("Mora perto da vítima?"))
sim += 1

resposta4 = (input("Devia para a vítima?"))
sim += 1

resposta5 = (input("Já trabalhou com a vítima? "))
sim += 1

if resposta1 == "n" and resposta2 == "n" and resposta3 == "n" and resposta4 == "n" and resposta5 == "n":
  print("Voce é inocente")

if resposta1 == "s" or resposta2 == "s" :
  print("Voce é suspeito")

if resposta3 == "s" or resposta4 == "s" :
  print("Voce é cumplice")

if resposta5 == "s" :
  print("Voce é o assassino")

"""# 17. Faça um programa que pergunte o preço de três produtos e informe qual produto você deve comprar, sabendo que a decisão é sempre pelo mais barato."""

produto1 = float(input("Qual o preco do primeiro produto: "))
produto2 = float(input("Qual o preco do segundo produto: "))
produto3 = float(input("Qual o preco do terceiro produto: "))

if produto1 < produto2 and produto1 < produto3 :
  print("Voce deve comprar o produto 1, pois é mais barato")

if produto2 < produto1 and produto2 < produto3 :
  print("Voce deve comprar o produto 2, pois é mais barato")

if produto3 < produto1 and produto3 < produto2 :
  print("Voce deve comprar o produto 3, pois é mais barato")